default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: ga_development

test:
  <<: *default
  database: ga_test

production:
   hostname: <%= ENV['HOSTNAME'] %>
   port: 3306
   username: <%= ENV['HOSTUSERNAME'] %>
   password: <%= ENV['HOSTPASSWORD'] %>
   database: <%= ENV['DATABASENAME'] %>
   adapter: mysql2
   encoding: utf8

