default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: ga_development

test:
  <<: *default
  database: ga_test

production:
  <<: *default
  database: <%= ENV['DATABASEURL'] %>
  username: <%= ENV['HOSTUSERNAME'] %>
  password: <%= ENV['HOSTPASSWORD'] %>

